[package]
name = "op_env_sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.3.0"
serde = {version = "1.0.144", features = ["derive"]}
serde_json = "1.0.85"
